### ISSUE TITLE
[1.18.2] JourneyMap Icon incorrect

### ISSUE THREAD

**Issue by Sandriell** [seymourimadeit/guardvillagers#100]
Was about to make an entity icon for this mod for use with Journeymap and noticed the mod already has one. There are however a few issues with the icon.

- First, the location is incorrect and should be in the folder "assets\guardvillagers\textures\entity_icon\guard\". This is to match the location of the actual entity textures which are in a "guard" folder.
- Secondly, due to having multiple guard textures, you have to have one icon to match each texture, with the icons having the same name as the texture.
- Finally, the icon should ideally be 16x16, whereas the current one is only 10x11. This will make it out of scale with existing icons.

**Comment by seymourimadeit** [comment]
To be honest I forgot that existed and I made that over a year ago (it isn't represented well on this repo specifically because I had to switch repos for reasons I won't get into)

Feel free to make the fixes yourself (for 1.19) via PR.  (unless I miraculously get the time to do it and do it myself lol)

ignore above I just added it in
