### ISSUE TITLE
[guardvillagers-1.19.2-1.5.6] Crossbow guards can't shoot faster, and "Have guards attempt to avoid firing into other friends? (Experimental)" in the config file does not work when enabled

### ISSUE THREAD

**Issue by v191949v** [seymourimadeit/guardvillagers#129]
The changelog in guardvillagers-1.19.2-1.5.6 says this:
- Reworked experimental friendly fire ai (needs to be enabled in config

    - Crossbow guards will try to move out of the way if they see a guard in front of them

- Made crossbow guards shoot faster

- Fixed bug with villager food ai

- Fixed bug with villager head animations

- Added new localization files
But I found that the first, second and third items don't work when I play, and there is no such problem in the next update version (guardvillagers-1.19.4-1.5.7)

**Comment by seymourimadeit** [comment]
Sorry, must've put in the wrong changelogs.

Quite honestly I won't be able to import the first 2 changes into 1.19.2 simply due to the lack of time I have and I don't want to be stuck developing for 1.19.2 (my mind may change but very low chance still). Anyone is free however to make a pull request for those changes in 1.19.2
