### ISSUE TITLE
Guard Villagers Incompatibilty with Mob Battle Mod

### ISSUE THREAD

**Issue by minecraftedleen** [seymourimadeit/guardvillagers#160]
I tried to make guards fight using mob battle mod by assigning them to different teams but they end up attacking their own teammates when they see an enemy guard

**Comment by seymourimadeit** [comment]
Can't recreate on an instance with only the mob battle mod and guard villagers mod. Could you try removing any ai-related mod and see if that fixes the problem (ie; ai improvements)

https://github.com/seymourimadeit/guardvillagers/assets/55965249/7fd72788-7108-4d84-ad90-08e9ad815bfb

**Comment by minecraftedleen** [comment]
ok I will test it again but it usually happened with large teams

**Comment by seymourimadeit** [comment]
I'm gonna keep it real with you. It's been over a month since a message was last posted here and no other tests have been conducted so far. If another test shows that this bug still happens I will investigate further, but I will have to close this for now since this is a month old and I don't want this issue page being filled with old reports all the time.
