### ISSUE TITLE
Guard Villager Tasks Causing TPS Buildup

### ISSUE THREAD

**Issue by DereC4** [seymourimadeit/guardvillagers#170]
Heyo, I've been running some metrics checks for the mods I used both for fun and to diagnose what may cause the most lag. Here's a report for Guard Villagers using Spark

![image](https://github.com/seymourimadeit/guardvillagers/assets/53978637/6165a156-6f5f-4fcc-a09c-23092d0f11aa)

Found out that Guard Villagers tasks use up a lot of TPS. I can see why, given that guards that need to stay on a position will constantly have to check for that spot, but I was wondering if there was any way you could optimize some of the tasks shown here. It appears the main cause of lag buildup is if one has many guards stationed at set blocks around the world, of which they will constantly check to path to that area. 

![image](https://github.com/seymourimadeit/guardvillagers/assets/53978637/56d07190-f379-4d76-b1a8-7bf596525c76)

Again, I understand it's no easy task to optimize this but could this maybe be looked at? It's a pressing issue on my servers where many players like to protect their villages with guards and station them at certain builds.

**Comment by seymourimadeit** [comment]
I'd appreciate it if you could expand this tab here so I can clearly see which specific goals are causing this problem.

Also I feel like it should be a no-brainer that having a bunch of mobs in one area would cause some amount of lag

UPDATE: I found a way to reduce this happening when guards are patrolling, however this update will have to be for 1.20 and up because I do not support 1.19 anymore.

![image](https://github.com/seymourimadeit/guardvillagers/assets/55965249/93b483c7-72b3-42b8-9d7e-c8341d1cfc84)

**Comment by DereC4** [comment]
It is indeed, as you say, a "no brainer", I was just hoping to bring this to your attention (I have around 8 guards in the village)

**Comment by DereC4** [comment]
Hope it helped!

**Comment by seymourimadeit** [comment]
> (I have around 8 guards in the village)

Ah, this brings things into perspective now.

I've already managed to find a fix for this issue, but as I stated previously it will only have to be for 1.20 and up. You are free to implement the new change to 1.19 soon (it's actually one line that needs to be changed lol)

**Comment by DereC4** [comment]
Oh neat do I just fork and then make a PR?

**Comment by seymourimadeit** [comment]
Yeah but I haven't pushed the commit to actually fix it yet

**Comment by DereC4** [comment]
w
