### ISSUE TITLE
1.19.2 Gaurds will endlessly reload their crossbow and not fire. which results in them only being able to kick

### ISSUE THREAD

**Issue by DrowsyDragonfruit** [seymourimadeit/guardvillagers#180]
the title says it all. any suggestions or advice?

**Comment by seymourimadeit** [comment]
Please tell us which version of the mod you're using, what other mods you're using, and if the issue is repeatable without any other mods interfering.

Keep in mind that I no longer update for 1.19.2 unless another person volunteers via pull request, so if its not caused by another mod then the chances of it being updated will depend on the overall severity of the issue.

**Comment by DrowsyDragonfruit** [comment]
im using the latest version for 1.19.2 i could fine. and i have some other villager mods. yet none should interfere with the firing of a crossbow.

**Comment by DrowsyDragonfruit** [comment]
though i understand you arent willing to update it. ill play around with it and see if any other mods cause interference.

**Comment by seymourimadeit** [comment]
I've tested alone in a 1.19.2 instance with only this mod and the crossbow mechanic works as normal, which leads me to think that this is caused by another mod. 

Unfortunately this means I will have to close this issue unless you have any further concerns, sorry, but this is just to keep the github clean from old issues being open forever

**Comment by DrowsyDragonfruit** [comment]
ofcourse! ur all fine. ill figure it out someday. thani you for being so willing to help though!
