### ISSUE TITLE
Feature of fighting back players (#211 is not solved)

### ISSUE THREAD

**Issue by Ch3225** [seymourimadeit/guardvillagers#217]
**further reply in #211 might be ignored by you, please check.**
You introduced FriendlyFire mod, it works but it will also introduce other problems, like making guards fully invincible. You didn't replied me on my further reply in #211 , so I just tried fixing this problem on my own by adding some codes.
**That's why I've modified the code to implement this and made a pull request #216.**  please also check it, which could be a solution of this issue. **

**Comment by seymourimadeit** [comment]
Sorry for not checking the replies in #211, life is busy and I had to focus on other things.
As for #216 I do like the idea in theory but I think it could just lead to abuse as it stands currently (insta-killing guards for armor while they don't attack you because you technically don't have a low reputation to get free armor). 
Of course, you could make that feature an addon to the mod using the same methods just inside a forge event instead.

I do have a plan for dealing with this though in the future where it's based off a 3 strike type of thing but I'm open to suggestions
