### ISSUE TITLE
[Crash] Ticking Entity

### ISSUE THREAD

**Issue by 123ghaksd** [seymourimadeit/guardvillagers#228]
[crash-2024-11-14_01.01.05-server.txt](https://github.com/user-attachments/files/17744244/crash-2024-11-14_01.01.05-server.txt)

Before you say 1.19.2 is no longer supported, the version clearly still has some form of instability. I believe it's best practice to insure that a mod is at least stable before a version is officially closed.  

Many people, like me, like playing with a large variety of mods. Many of which have developers that cannot afford to update frequently. It's sort of against what MC modding is to just leave a previous version unstable due to Mojang releasing a new version. 

This is a great mod that I'd love to have in my super refined modpack, but I'm contemplating removing it. Would truly be grateful for just a patch fixing the issue, as would others. 

Mod version: 1.5.9
MC Version: 1.19.2

**Comment by seymourimadeit** [comment]
> the version clearly still has some form of instability

Considering how this is the very first report I've gotten about this type of crash in recent years I think it is still safe to say that for the vast majority of users the mod version for 1.19.2 is still stable

The actual crash report seems to be referencing the Cloaked mod's loot table editing system somehow injecting into the loot table system from Guard Villagers (which only serves to edit how Guard's get their armor equipped), which leads me to suspect that the main cause of the problem may be Cloaked and potentially the loot integrations mod too.

I believe you should try reporting this issue to the Cloaked mod first and then the loot integration mod, and if the problem is found to be on this mod's side then you can try to make a patch for this crash yourself (I would love to make a patch for 1.19.2, but my main focus is on updating for the latest version and my personal life limits my available free time to do modding).

**Comment by 123ghaksd** [comment]
Ok, sorry thought it was this mod. Thanks for the explanation. That seems about right with the loot tables though cause I noticed some issues. Unfortunately Cloaked is completely abandoned. Sucks cause Cloaked is IMO the best cape mod out there by far.
