### ISSUE TITLE
Equipment

### ISSUE THREAD

**Issue by aburone** [seymourimadeit/guardvillagers#27]
I assumed that this was intentional. But given your last update fixes bows not respecting enchantments...

I tried in the past giving different equipment to guards and for what I could observe they always ignore whatever enchantments/abilities the armor or shield has.
Some swords enchants seem to be working but certainly not all
One extreme case is. I have A LOT of Mekanism's Meka suits, go I gave them to several guards. Wearing them the guard should be basically invulnerable... They aren't, they get 0 armor (the suits where fully charged)

I'm playing with quite beef up mobs, so if I want the guards to be useful I need them to accept any op equipment I give to them. And I can't really be sure if any enchantments is working unless it has some visual effect. A list of currently active effects on the guard UI would be wonderful.

Sorry about the long issue(s). I really love your mod

**Comment by seymourimadeit** [comment]
With your case with the Meka suits you have to go ask the creator of that mod to make them work for entities besides the player.  Actually most of what you report is most likely caused by those mods hardcoding those enchantments to be player only, please go ask them instead of us, and if something has to be done on our side they will have to tell us.

**Comment by aburone** [comment]
I gave you the example of the mekasuit. But I specifically said that the guards are ignoring any enchantment on equipment (not the meka sut, it CAN'T be enchanted)

If you're gonna be an ass. Don't provide an issues section
