### ISSUE TITLE
[Suggestion] Guard Block

### ISSUE THREAD

**Issue by judicius** [seymourimadeit/guardvillagers#51]
Would it be possible to set the block that villagers use to become guards as the armor stand? Would it also then be possible that if a new guard is created by the armor stand they will take whatever is on the armor stand to equip themselves?

**Comment by ProfessorBustanut** [comment]
i was thinking footlocker they die so easy that they should have a playerless way of replenishing guards and when they do die there items go back into the footlocker instead of falling on the ground and despawning
also a guard post so you can tell them where the best place to defend is instead of them just jogging around the village

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
